name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  TS_NODE_PROJECT: ./tsconfig.json
  TS_NODE_BASEURL: ./
  NODE_OPTIONS: '-r tsconfig-paths/register'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        npm install -D tsconfig-paths ts-node @types/node
        
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Verify TypeScript Configuration
      run: |
        echo "Checking tsconfig paths..."
        npx tsc --project tsconfig.json --noEmit
        
    - name: Run Playwright tests
      run: npm run test
      env:
        DEBUG: pw:api*
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
          playwright/.cache/
        retention-days: 30